name: Employeefrontend DevSecOps workflow

on: 
  push: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 Download the Source Code
        uses: actions/checkout@v3.5.3

      - name: Step 2 Install Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 'v18.16.1'

      - name: Step 3 Install Dependecies 
        run: npm install

      - name: Step 4 Sonarcloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:  
          args: >
            -Dsonar.organization=nourayd
            -Dsonar.projectKey=nourayd_employeefrontend-fursan-track3
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
